version: '3'

services:
  app:
    build: .
    container_name: app
    command: ./.docker/entrypoint.sh
    tty: true
    volumes:
      - .:/home/python/app
      - ./logs:/logs
    ports:
      - 8000:8000
